config/routes.rb
BusGripesApp::Application.routes.draw do

  devise_for :users

  resources :gripes

  root to: "homepage#index"

  get '/camera', to: "camera#index"

  get '/maps', to: "maps#index"
  post '/maps', to: "maps#index"

  get '/about', to: "about#index"

  match 'message' => 'message#new', :as => 'contact', :via => :get
  match 'message' => 'message#create', :as => 'contact', :via => :post
  

end

app/models/gripe.rb
class Gripe < ActiveRecord::Base
  attr_accessible :bus_stop, :comment, :gripe1, :gripe2, :gripe3, :gripe4, :latitude, :longitude, :picture, :user_id, :bus_number, :address, :registration, :occurence, :gripe_photo

  mount_uploader :gripe_photo, GripePhotoUploader 

  belongs_to :user

  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude, :address => :address

  after_validation :geocode, :reverse_geocode # auto-fetch address 


end

app/models/message.rb
class Message < ActiveRecord::Base

    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming

    attr_accessor :name, :email, :subject, :body

    validates :name, :email, :subject, :body, :presence => true
    validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
    
    def initialize(attributes = {})
      attributes.each do |name, value|
        send("#{name}=", value)
      end
    end

    def persisted?
      false
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :gripes, :foreign_key => :user_id
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || new_gripe_path
    end
  end

  def after_log_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      super
    else
      stored_location_for(resource) || request.referer || new_gripe_path
    end
  end


end

app/controllers/camera_controller.rb
class CameraController < ApplicationController

  def index

  end
  
end

app/controllers/gripes_controller.rb
class GripesController < ApplicationController
  # GET /gripes
  # GET /gripes.json

  before_filter :authenticate_user!

  def index
    @gripes = Gripe.all
    @hash = Gmaps4rails.build_markers(@gripes) do |gripe, marker |
      marker.lat gripe.latitude
      marker.lng gripe.longitude
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gripes }
    end
  end

  # GET /gripes/1
  # GET /gripes/1.json
  def show
    @gripe = Gripe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gripe }
    end
  end

  # GET /gripes/new
  # GET /gripes/new.json
  def new
    @gripe = Gripe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gripe }
    end
  end

  # GET /gripes/1/edit
  def edit
    @gripe = Gripe.find(params[:id])
  end

  # POST /gripes
  # POST /gripes.json
  def create

    @gripe = Gripe.new(params[:gripe])
    @gripe.user_id = current_user.id
    @gripe.latitude = @gripe.latitude.to_f
    @gripe.longitude = @gripe.longitude.to_f
    if @gripe.occurence.nil?
      @gripe.occurence = Time.now
    end
    @gripe.save
    #Removed the address line as it was overriding the lat long and also called @gripe.save
    respond_to do |format|
      if @gripe.save
        format.html { redirect_to @gripe, notice: 'Gripe successfully created.' }
        format.json { render json: @gripe, status: :created, location: @gripe }
      else
        format.html { render action: "new" }
        format.json { render json: @gripe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gripes/1
  # PUT /gripes/1.json
  def update
    @gripe = Gripe.find(params[:id])

    respond_to do |format|
      if @gripe.update_attributes(params[:gripe])
        format.html { redirect_to @gripe, notice: 'Gripe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gripe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gripes/1
  # DELETE /gripes/1.json
  def destroy
    @gripe = Gripe.find(params[:id])
    @gripe.destroy

    respond_to do |format|
      format.html { redirect_to gripes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @gripe = Gripe.new
    @gripes = Gripe.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gripes }

      # render :partial => '/gripes/_form.html.erb'

    end
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
skip_before_filter :verify_authenticity_token
  def index
    @input = params[:gripe_map_select]
    # Input numbers were coming out as string so had to compare below to a sting of 0 or 1.
    # Also the params were always passing back a number so "Gripe.where(gripe1: @input)" would be looking for a gripe where gripe1 = "3"
    # But you don't have gripes stored as a number, you are storing it as the text so in the select form i removed the numbers so you are now passing back the name of the gripe.
    # i.e. "Gripe.where(gripe1: 'Motorbike Accident')".
    if @input == "0"
      flash[:notice] = "Please choose a gripe!"
    elsif @input == "1"
      @gripes = Gripe.all
    else
      @gripes = Gripe.where(gripe1: @input) + Gripe.where(gripe2: @input) + Gripe.where(gripe3: @input) + Gripe.where(gripe4: @input)
    end

    #Had to change the block below, you had user in there rather than gripe.
    # line 19 looked like "@hash = Gmaps4rails.build_markers(@users) do |user, marker |"
    @hash = Gmaps4rails.build_markers(@gripes) do |gripe, marker |
    marker.lat gripe.latitude
    marker.lng gripe.longitude
    end
  

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gripes }
    end  
  end
  
end

app/controllers/message_controller.rb
class MessageController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    params[:user].merge!(remember_me: 1)
    super
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gripes_helper.rb
module GripesHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/about/index.html.erb
<div class="about-container">
  <h3>About</h3>
  <hr>
  <p>BusGripes allows you to track and map bad bus driving.See where there are problems on the bus network and have a place to make your voice heard.</p>
  <hr>
  <p><span class="bold-start">The Problem:</span> Most travel organisations, like TFL, can  measure if a bus runs on time, how much fuel it uses and other similar metrics, but they don't measure the "quality" of bus driving. As bus users we all have a story or two to tell on this front</p>
  <p><span class="bold-start">The Solution:</span> BusGripes reveals the problems  with the collective help of you, the public transport users. You can report an incident giving up to 4 different issues, your location, time of incident and upload a comment and picture. </p>
  <p><span class="bold-start">Next Steps:</span> Together we can use "big data" to make our public transport system run better. We use this data to convince the bus companies and travel orgniastions to make improvements.</p>
  <p><span class="bold-start">Get Inolved:</span> Please get in touch and let us know how we can improve this service, to tell us new problems to track, or if you have any bright ideas!</p>
  <a href="#" class="donate-button">donate</a>
  <p> To keep this service running and the servers humming please make a contribution of £3 (cheaper than a London Beer!).</p>
  <br>
  <br>
</div>

app/views/camera/index.html.erb
<video height="480" id="video" width="500"></video>
<button id="snap">Snap Photo</button>
<canvas height="480" id="canvas" width="500"></canvas>

app/views/gripes/_form.html.erb
<div class="new-gripe">
  <%= form_for(@gripe) do |f| %>
  <% if @gripe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gripe.errors.count, "error") %>
        prohibited this gripe from being saved:
      </h2>
      <ul>
        <% @gripe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <hr/>
  <h3>What's the bus number?</h3><span class="optional"> (optional)</span>
  <div class="field">
    <%#= f.label :bus_number %>
    <%= f.text_field :bus_number, :placeholder => "e.g. 12" %>
  </div>

  <hr/>
  <h3>What's the registration number?</h3><span class="optional"> (optional)</span>
  <div class="field">
    <%#= f.label :registration %>
    <%= f.text_field :registration, :placeholder => "e.g. BU05 XXX", :pattern => '^([A-Z]{3}\s?(\d{3}|\d{2}|d{1})\s?[A-Z])|([A-Z]\s?(\d{3}|\d{2}|\d{1})\s?[A-Z]{3})|(([A-HK-PRSVWY][A-HJ-PR-Y])\s?([0][2-9]|[1-9][0-9])\s?[A-HJ-PR-Z]{3})$'  %>
  </div>

  <hr/>
  <h3>What's your gripe?  </h3>
  <p class="required">(At least one required)</p>
  <div class="field">
    <%= f.label :gripe1%>
    <%= f.select(:gripe1, options_for_select([['choose a gripe', 'n/a'],['Dangerous driving', 'Dangerous driving'], ['Bicycle accident', 'Bicycle accident'],['Wheelchair problem', 'Wheelchair problem'],['Child buggy problem', 'Child buggy problem'],['Jumped Red Lights', 'Jumped Red Lights'],['Didn\'t stop at pedestrian crossing', 'Didn\'t stop at pedestrian crossing'],['Motorbike accident', 'Motorbike accident'],['Pedestrian accident', 'Pedestrian accident'],['Didn\'t stop at bus stop', 'Didn\'t stop at bus stop']],0), :required => true) %>
  </div>
  <div class="field">
    <%= f.label :gripe2 %>
      <%= f.select(:gripe2, options_for_select([['choose a gripe', 'n/a'],['Dangerous driving', 'Dangerous driving'], ['Bicycle accident', 'Bicycle accident'],['Wheelchair problem', 'Wheelchair problem'],['Child buggy problem', 'Child buggy problem'],['Jumped Red Lights', 'Jumped Red Lights'],['Didn\'t stop at pedestrian crossing', 'Didn\'t stop at pedestrian crossing'],['Motorbike accident', 'Motorbike accident'],['Pedestrian accident', 'Pedestrian accident'],['Didn\'t stop at bus stop', 'Didn\'t stop at bus stop']],0)) %>
  </div>
  <div class="field">
    <%= f.label :gripe3 %>
      <%= f.select(:gripe3, options_for_select([['choose a gripe', 'n/a'],['Dangerous driving', 'Dangerous driving'], ['Bicycle accident', 'Bicycle accident'],['Wheelchair problem', 'Wheelchair problem'],['Child buggy problem', 'Child buggy problem'],['Jumped Red Lights', 'Jumped Red Lights'],['Didn\'t stop at pedestrian crossing', 'Didn\'t stop at pedestrian crossing'],['Motorbike accident', 'Motorbike accident'],['Pedestrian accident', 'Pedestrian accident'],['Didn\'t stop at bus stop', 'Didn\'t stop at bus stop']],0)) %>
  </div>
  <div class="field">
    <%= f.label :gripe4 %>
      <%= f.select(:gripe4, options_for_select([['choose a gripe', 'n/a'],['Dangerous driving', 'Dangerous driving'], ['Bicycle accident', 'Bicycle accident'],['Wheelchair problem', 'Wheelchair problem'],['Child buggy problem', 'Child buggy problem'],['Jumped Red Lights', 'Jumped Red Lights'],['Didn\'t stop at pedestrian crossing', 'Didn\'t stop at pedestrian crossing'],['Motorbike accident', 'Motorbike accident'],['Pedestrian accident', 'Pedestrian accident'],['Didn\'t stop at bus stop', 'Didn\'t stop at bus stop']],0)) %>
  </div>
  <hr/>
  <div class="field picture-field">
    <h3>Add a picture</h3><span class="optional"> (optional)</span>
    <div class="upload-file-container">
      <div class="upload-button">
        <span>upload</span>
        <%= f.file_field :gripe_photo, :class => "upload" %>
      </div>
      <!-- <button>select file  </button> -->
<!--       <div class="take_pic_wrapper">
        Or 
        <%#= link_to('take photo', "/camera", :id => "take-photo")  %>
      </div> -->
    </div>
  </div>
  <hr/>
  <div class="field">
    <h3>Add a comment</h3><span class="optional"> (optional)</span>
    <br/>
    <%= f.text_area :comment %>
  </div>

  <hr/>
  <h3>Where did this happen?</h3>
  <p class="required">(required)</p>
  <div class="geolocation-button">current location</div>
    <%= f.hidden_field :latitude , :id => "gripe_latitude" %>
    <%= f.hidden_field :longitude, :id => "gripe_longitude" %>
  <p class="or">or enter address below</p>
  <p id="comms"></p>  
  <div class="field address-input">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <hr/>
  <div class="field">
    <h3>When did this happen?</h3>
    <p class="required">(required)</p>
    <div class="time-button">past 10 mins</div>
    <p class="or">or enter time below</p>
    <p class="ten-min-selected"></p>
    <div class="date-time-select">
      <%= f.datetime_select(:occurence, prompt: true) %>
    </div>
  </div>
  
  <hr/>
   <%= f.submit "Submit Gripe", :class => "submit-gripe-btn" %>  

  <% end %> 
</div>

app/views/gripes/edit.html.erb
<h1>Editing gripe</h1>

<%= render 'form' %>

<%= link_to 'Show', @gripe %> |
<%= link_to 'Back', gripes_path %>

app/views/gripes/index.html.erb
<%= form_for(@gripe) do |f| %>
  <% if @gripe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gripe.errors.count, "error") %>
        prohibited this gripe from being saved:
      </h2>
      <ul>
        <% @gripe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <hr/>
  <h3>What's the bus number?        </h3>
  <div class="field">
    <%= f.label :bus_number %>
    <br/>
    <%= f.text_field :bus_number %>
  </div>

  <hr/>
  <h3>What's your gripe?  </h3>
  <div class="field">
    <%= f.label :gripe1 %>
    <br/>
    <%= f.select(:gripe1, options_for_select([['choose a gripe', 0],['All Gripes', 1], ['Bicycle accident', 2],['Wheelchair problem', 3],['Child buggy problem', 4],['Jumped Red Lights', 5],['Didn\'t stop at pedestrian crossing',6],['Motorbike accident',7],['Pedestrian accident',8],['Bus didn\'t stop', 9]],0) ) %>
  </div>
  <div class="field">
    <%= f.label :gripe2 %>
    <br/>
    <%= f.select(:gripe2, options_for_select([['choose a gripe', 0],['All Gripes', 1], ['Bicycle accident', 2],['Wheelchair problem', 3],['Child buggy problem', 4],['Jumped Red Lights', 5],['Didn\'t stop at pedestrian crossing',6],['Motorbike accident',7],['Pedestrian accident',8],['Bus didn\'t stop', 9]],0) ) %>
  </div>
  <div class="field">
    <%= f.label :gripe3 %>
    <br/>
    <%= f.select(:gripe3, options_for_select([['choose a gripe', 0],['All Gripes', 1], ['Bicycle accident', 2],['Wheelchair problem', 3],['Child buggy problem', 4],['Jumped Red Lights', 5],['Didn\'t stop at pedestrian crossing',6],['Motorbike accident',7],['Pedestrian accident',8],['Bus didn\'t stop', 9]],0) ) %>
  </div>
  <div class="field">
    <%= f.label :gripe4 %>
    <br/>
    <%= f.select(:gripe4, options_for_select([['choose a gripe', 0],['All Gripes', 1], ['Bicycle accident', 2],['Wheelchair problem', 3],['Child buggy problem', 4],['Jumped Red Lights', 5],['Didn\'t stop at pedestrian crossing',6],['Motorbike accident',7],['Pedestrian accident',8],['Bus didn\'t stop', 9]],0) ) %>
  </div>
  <hr/>
  <div class="field">
    <h3>Add a picture</h3>
    <br/>
    <div class="select_file_field">
      <div class="select_file_wrapper">
        <%= f.file_field :picture %>
      </div>
      <button>select file  </button>
      <div class="take_pic_wrapper">
        Or 
        <%= link_to('take photo', "/camera", :id => "take-photo")  %>
      </div>
    </div>
  </div>
  <hr/>
  <div class="field">
    <h3>Add a comment</h3>
    <br/>
    <%= f.text_area :comment %>
  </div>
  <hr/>
  <h3>Where did this happen?</h3>
  <div class="field">
    <%= f.label :address %>
    <br/>
    <%= f.text_field :address %>
  </div>
  <b>or enter bus stop</b>
  <br/>
  <div class="field">
    <%= f.label :bus_stop %>
    <br/>
    <%= f.text_field :bus_stop %>
    <!-- .field
    -->
    <!--   = f.submit
    -->
  </div>
  <button class="create_gripe">create gripe</button>
  <hr/>
<% end %>

app/views/gripes/new.html.erb
<div class="new-gripe-wrapper">
  <h2>New gripe</h2>
  <p>Tell us about your experience</p>

  <%= render 'form' %>

  <%= link_to 'Back', gripes_path %>
<div>

app/views/gripes/show.html.erb
<div class="show-page">
  <h2>Your Gripe</h2>

  <p class="notice"><%= notice %></p>

  <p>Your gripe has been submitted with the following information:</p>
  

    <p>
    <b>Occurence:</b>
    <%= @gripe.occurence %>
  </p>

  <p>
    <b>Bus Number:</b>
    <%= @gripe.bus_number %>
  </p>
  <p>
    <b>Registration:</b>
    <%= @gripe.registration %>
  </p>
  <p>
    <b>Gripe1:</b>
    <%= @gripe.gripe1 %>
  </p>

  <p>
    <b>Gripe2:</b>
    <%= @gripe.gripe2 %>
  </p>

  <p>
    <b>Gripe3:</b>
    <%= @gripe.gripe3 %>
  </p>

  <p>
    <b>Gripe4:</b>
    <%= @gripe.gripe4 %>
  </p>

  <p>
      <b>Image:</b>
      <%= image_tag @gripe.gripe_photo.basic.url %>
  </p>

  <p>
    <b>Comment:</b>
    <%= @gripe.comment %>
  </p>
  
  <p>
    <b>Address:</b>
    <%= @gripe.address %>
  </p>
  <br />
  <br />
  <br />
<!--   <p>
    <b>Map lat:</b>
    <%#= @gripe.latitude %>
  </p>

  <p>
    <b>Map long:</b>
    <%#= @gripe.longitude %>
  </p> -->



</div>

app/views/homepage/index.html.erb
<div class="homepage-container">
   <p class="tagline">Tracking + mapping bus driving      </p>
  <div>
   <% if user_signed_in? %>
   <p class="logged-in-email">Logged in:<%= current_user.email %></p>
    <% end %>      
  </div> 


  <div class="login-signup">
    <%= link_to 'Sign up', new_user_registration_path, :class => "login-signup-button" %>
    <%= link_to 'Login', new_user_session_path, :class => "login-signup-button" %>
  </div>
  <div class="homepage-about">
    <%= link_to('about', '/about', :data => { :'data-transition' => 'flip'})  %>
  </div>
</div>

app/views/layouts/application.html.erb
<head>
  <title>BusGripesApp</title>
  <meta name="description" content="Mapping and tracking bad bus driving.">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.2/normalize.min.css" rel="stylesheet" type="text/css"></link>
  <link href='https://fonts.googleapis.com/css?family=Muli' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!-- google maps -->
  <script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry,visualization" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
  <%= javascript_include_tag "application" %>
  <!-- google fonts --> 
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <header>
      <h1 class="title">BusGripes</h1>
      <%#= image_tag "sadface-1.png", :class => "logo" %>
      <p class="tagline">mapping bad bus driving</p>
    <nav class="menu">
      <button>menu</button>
      <ul>
        <li>
        <%= link_to('about', '/about' )  %>
        </li>
          <li>
        <%= link_to('donate', '#', :class => 'donate-button' )  %>
        </li>
        <li>
          <%= link_to 'new gripe', new_gripe_path  %>
        </li>
        <li>
          <%= link_to 'maps', maps_path  %>
        </li>
        <li>
          <%= link_to('contact / feedback', 'mailto:info@busgripes.com') %>
        </li>
          <li>
            <div >
              <% if user_signed_in? %>
                <p class="logged-in-email">Logged in:<%= current_user.email %></p>
                <div class="edit_login_logout">
                  <%= link_to 'Edit Profile', edit_user_registration_path, :class => "edit-logout"%>
                  |
                  <%= link_to 'Logout',  destroy_user_session_path, method: :delete, :class => "edit-logout" %>
                </div>
              <% else %>
                <div class="edit_login_logout">
                  <%= link_to 'Sign up', new_user_registration_path, :class => "edit-logout" %>
                  /
                  <%= link_to 'Login', new_user_session_path, :class => "edit-logout" %>
                </div>
              <% end %>
              <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              <% end %>
            </div>
          </li>  
        </ul>
      </nav>   
    </header>
    

    <div>
      <%= yield %>
    </div>  

    <div class="gripe-map-btns-wrapper">
      <ul>
        <li>
          <%= link_to('new gripe', new_gripe_path, :class => "footer-gripe")%>
        </li> 

        <li>
          <%= link_to('maps', "/maps", :class => "footer-map" )  %>
        </li>
      </ul>
    </div>

  </div><!-- end of container -->
</body>

app/views/maps/index.html.erb
<div class="map-page-container">
  <h2>Map of bus problems</h2>
  <%= javascript_tag "var gripes_data = #{@gripes.to_json};" %>
  
  <div class="map-select-container">
    <form action="/maps" method="POST" name="gripe_map_select" >
      <%= select_tag(:gripe_map_select, options_for_select([['All gripes', 1], ['Bicycle accident'],['Wheelchair problem'],['Child buggy problem'],['Jumped Red Lights'],['Didn\'t stop at pedestrian crossing'],['Motorbike accident'],['Pedestrian accident'],['Bus didn\'t stop']],0), :class => "gripe_map_select") %>
      <button>Show Map</button>
    </form>
    <div id="map-canvas">
      <div id="map"></div>
    </div>   
  </div>
</div>

app/views/message/new.html.erb
<%= form_for @message, :url => contact_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send" %>
  </fieldset>
<% end %>